#include "Motor20.hpp"
#include <cmath>

//
// Compute raw signal value: 
// Reads "length" bits starting from buff[byte], bit position "bit"
// NOTE: same logic as compute_signal_raw_value(...)
//
template<typename T>
T Motor20::extract(const unsigned char* buff, int byte, int bit, int length)
{
    uint32_t raw = 0;

    // Copy two bytes to ensure we cover cross-boundary bits
    raw = (buff[byte] << 8) | buff[byte + 1];

    // Shift to remove unwanted high bits
    raw >>= (16 - bit - length);

    // Mask out the lower bits
    uint32_t mask = (1u << length) - 1u;
    raw &= mask;

    return static_cast<T>(raw);
}

//
// Decode Motor20 PDU
//
void Motor20::decode(const unsigned char* buff)
{
    // mo_fahrpedalrohwert_01:
    //   byte = 1
    //   bit  = 4
    //   len  = 8
    uint8_t raw = extract<uint8_t>(buff, 1, 4, 8);

    Motor20Data result;

    // Valid according to autogenerated spec:
    //    raw <= 254
    if (raw <= 254)
    {
        result.valid = true;
        result.gas_percent = raw * 0.4f;   // physical scaling
    }
    else
    {
        result.valid = false;
        result.gas_percent = 0.0f;
    }

    out = result;
}
