#include "Motor20.hpp"
#include <cmath>

//
// Compute raw signal value: 
// Reads "length" bits starting from buff[byte], bit position "bit"
// NOTE: same logic as compute_signal_raw_value(...)
//
template<typename T>
T Motor20::extract(const unsigned char* buff, int byte, int bit, int length)
{
    uint32_t raw =
        (buff[byte]     << 16) |
        (buff[byte + 1] << 8 ) |
        (buff[byte + 2]);

    raw >>= (24 - bit - length);
    raw &= ((1u << length) - 1u);

    return static_cast<T>(raw);
}


//
// Decode Motor20 PDU
//
void Motor20::decode(const unsigned char* buff)
{
    // mo_fahrpedalrohwert_01:
    //   byte = 1
    //   bit  = 4
    //   len  = 8
    uint8_t raw = extract<uint8_t>(buff, 1, 4, 8);

    Motor20Data result;

    // Valid according to autogenerated spec:
    //    raw <= 254
    if (raw <= 254)
    {
        result.valid = true;
        result.gas_percent = raw * 0.4f;   // physical scaling
    }
    else
    {
        result.valid = false;
        result.gas_percent = 0.0f;
    }

    out = result;
}
