/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an AS IS BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_TRAINED_ONNX_H_
#define _EI_CLASSIFIER_TRAINED_ONNX_H_

#define INCBIN_STYLE INCBIN_STYLE_SNAKE

// todo: no idea how to do this
#ifdef EI_MODEL_SECTION
#define INCBIN_OUTPUT_SECTION EI_MODEL_SECTION
#endif

#include "edge-impulse-sdk/third_party/incbin/incbin.h"

INCBIN(incbin_trained_onnx, "trained.onnx");

const unsigned char *trained_onnx = gincbin_trained_onnx_data;
unsigned int trained_onnx_len = gincbin_trained_onnx_size;

const char *trained_onnx_hash = "29003690ee21fdc0331b591eefebc4e98350558c";

#endif // _EI_CLASSIFIER_TRAINED_ONNX_H_
