#pragma once

#include <array>
#include <cstdint>

#include "AdmaCommonTypes.hpp"

namespace adma::protocol {

#pragma pack(push, 1)

struct AdmaDataV32 {
  AdmaStaticHeader staticHeader;
  AdmaDynamicHeader dynamicHeader;
  unsigned char gpsStatus;
  unsigned char gpsTriggerStatus;
  unsigned char evkStatus;
  int8_t statuscount;
  Reserved4 reservedStatus1;
  unsigned char dataError1;
  unsigned char dataError2;
  unsigned char dataWarn1;
  unsigned char dataErrorHW;
  Reserved4 reservedError1;
  SensorBody sensorsBodyX;
  SensorBody sensorsBodyY;
  SensorBody sensorsBodyZ;
  Vector3 rateBody;
  Vector3 rateHorizontal;
  Vector3 accBody;
  Vector3 accHorizontal;
  Vector3 accBodyPOI1;
  Vector3 accBodyPOI2;
  Vector3 accBodyPOI3;
  Vector3 accBodyPOI4;
  Vector3 accBodyPOI5;
  Vector3 accBodyPOI6;
  Vector3 accBodyPOI7;
  Vector3 accHorizontalPOI1;
  Vector3 accHorizontalPOI2;
  Vector3 accHorizontalPOI3;
  Vector3 accHorizontalPOI4;
  Vector3 accHorizontalPOI5;
  Vector3 accHorizontalPOI6;
  Vector3 accHorizontalPOI7;
  Vector2 extVelAnalog;
  int16_t extveldigx;
  int16_t extveldigy;
  uint16_t extveldigpulsesx;
  int16_t extveldigpulsesy;
  Vector2 extVelCorrected;
  uint32_t extbaropressure;
  Reserved4 reservedSpace1;
  int32_t extbaroheight;
  int32_t extbaroheightcorrected;
  Reserved4 reservedSpace2;
  Reserved4 reservedSpace3;
  Miscellaneous misc;
  Miscellaneous miscPOI1;
  Miscellaneous miscPOI2;
  Miscellaneous miscPOI3;
  Miscellaneous miscPOI4;
  Miscellaneous miscPOI5;
  Miscellaneous miscPOI6;
  Miscellaneous miscPOI7;
  uint16_t trigrising1;
  uint16_t trigfalling1;
  uint16_t trigrising2;
  uint16_t trigfalling2;
  uint16_t trigrising3;
  uint16_t trigfalling3;
  uint16_t trigrising4;
  uint16_t trigfalling4;
  uint16_t systemta;
  int16_t systemtemp;
  uint16_t systemtimesinceinit;
  uint16_t systemdspload;
  GNSSPosition gpsPosAbs;
  GNSSPosition gpsPosRel;
  uint16_t gpsstddevlat;
  uint16_t gpsstddevlon;
  uint16_t gpsstddevheight;
  Reserved2 reservedSpace4;
  int16_t gpsvelframex;
  int16_t gpsvelframey;
  int16_t gpsvelframez;
  uint16_t gpsvellatency;
  Vector3 gpsStdDevVel;
  uint32_t gpstimemsec;
  uint16_t gpstimeweek;
  uint16_t gpstrigger;
  uint16_t gpsdiffage;
  unsigned char gpssatsused;
  unsigned char gpssatsvisible;
  Reserved4 reservedSpace5;
  unsigned char gpslogdelay;
  unsigned char gpsreceiverload;
  unsigned char gpsbasenr[4];
  Reserved2 reservedSpace6;
  int16_t insroll;
  int16_t inspitch;
  uint16_t insyaw;
  uint16_t gpscog;
  int32_t gpsheight;
  int16_t undulation;
  Reserved2 reservedSpace7;
  int32_t insHeight;
  Reserved4 reservedSpace8;
  int32_t insHeightPOI1;
  int32_t insHeightPOI2;
  int32_t insHeightPOI3;
  int32_t insHeightPOI4;
  int32_t insHeightPOI5;
  int32_t insHeightPOI6;
  int32_t insHeightPOI7;
  Reserved4 reservedSpace9;
  uint32_t instimemsec;
  uint16_t instimeweek;
  int16_t leapseconds;
  GNSSPosition insPosAbs;
  GNSSPosition insPosRel;
  GNSSPosition insPosAbsPOI1;
  GNSSPosition insPosRelPOI1;
  GNSSPosition insPosAbsPOI2;
  GNSSPosition insPosRelPOI2;
  GNSSPosition insPosAbsPOI3;
  GNSSPosition insPosRelPOI3;
  GNSSPosition insPosAbsPOI4;
  GNSSPosition insPosRelPOI4;
  GNSSPosition insPosAbsPOI5;
  GNSSPosition insPosRelPOI5;
  GNSSPosition insPosAbsPOI6;
  GNSSPosition insPosRelPOI6;
  GNSSPosition insPosAbsPOI7;
  GNSSPosition insPosRelPOI7;
  Vector3 insVelHor;
  Vector3 insVelFrame;
  Vector3 insVelHorPOI1;
  Vector3 insVelHorPOI2;
  Vector3 insVelHorPOI3;
  Vector3 insVelHorPOI4;
  Vector3 insVelHorPOI5;
  Vector3 insVelHorPOI6;
  Vector3 insVelHorPOI7;
  uint16_t insstddevlat;
  uint16_t insstddevlong;
  uint16_t insstddevheight;
  Reserved2 reservedSpace10;
  int8_t insstddevvelx;
  int8_t insstddevvely;
  int8_t insstddevvelz;
  int8_t insstddevroll;
  int8_t insstddevpitch;
  int8_t insstddevyaw;
  Reserved2 reservedSpace11;
  int16_t an1;
  int16_t an2;
  int16_t an3;
  int16_t an4;
};

struct AdmaDataV333 {
  AdmaStaticHeader staticHeader;
  AdmaDynamicHeader dynamicHeader;
  unsigned char gnssStatus;
  unsigned char signalInStatus;
  unsigned char miscStatus;
  int8_t statuscount;
  unsigned char kfStatus;
  unsigned char reservedStatus1[3];
  unsigned char dataError1;
  unsigned char dataError2;
  unsigned char dataWarn1;
  unsigned char dataError3;
  Reserved4 reservedError1;
  SensorBody sensorsBodyX;
  SensorBody sensorsBodyY;
  SensorBody sensorsBodyZ;
  Vector3 ratesBody;
  Vector3 ratesHorizontal;
  Vector3 accBody;
  Vector3 accHorizontal;
  Vector3 accBodyPOI[8];
  Vector3 accHorizontalPOI[8];
  Vector2 extVelAnalog;
  int16_t extveldigx;
  int16_t extveldigy;
  uint16_t extveldigpulsesx;
  int16_t extveldigpulsesy;
  Vector2 extVelCorrected;
  Reserved4 reservedData1;
  Reserved4 reservedData2;
  Reserved4 reservedData3;
  Reserved4 reservedData4;
  Reserved4 reservedData5;
  Reserved4 reservedData6;
  Miscellaneous misc;
  Miscellaneous miscPOI[8];
  uint16_t trigrising1;
  uint16_t trigfalling1;
  uint16_t trigrising2;
  uint16_t trigfalling2;
  uint16_t trigrising3;
  uint16_t trigfalling3;
  uint16_t trigrising4;
  uint16_t trigfalling4;
  uint16_t systemta;
  int16_t systemtemp;
  uint16_t systemtimesinceinit;
  uint16_t systemdspload;
  GNSSPosition posAbs;
  GNSSPosition posRel;
  uint16_t gnssstddevlat;
  uint16_t gnssstddevlon;
  uint16_t gnssstddevheight;
  Reserved2 reservedSpace4;
  int16_t gnssvelframex;
  int16_t gnssvelframey;
  int16_t gnssvelframez;
  uint16_t gnssvellatency;
  Vector3 gnssStdDevVel;
  uint32_t gnsstimemsec;
  uint16_t gnsstimeweek;
  uint16_t gnsstrigger;
  uint16_t gnssdiffage;
  unsigned char gnsssatsused;
  unsigned char gnsssatsvisible;
  unsigned char gnsssatsdualantused;
  unsigned char gnsssatsdualantvisible;
  Reserved2 reservedSpace5;
  unsigned char gnsslogdelay;
  unsigned char gnssreceiverload;
  unsigned char gnssbasenr[4];
  Reserved2 reservedSpace6;
  int16_t insroll;
  int16_t inspitch;
  uint16_t insyaw;
  uint16_t gnsscog;
  int32_t gnssheight;
  int16_t undulation;
  Reserved2 reservedSpace7;
  uint32_t gnssDualAntTimeMsec;
  uint16_t gnssDualAntTimeWeek;
  Reserved2 reservedSpace8;
  uint16_t gnssDualAntHeading;
  int16_t gnssDualAntPitch;
  Reserved4 reservedSpace9;
  unsigned char gnssdualantstdevheading;
  unsigned char gnssdualantstddevpitch;
  uint16_t gnssdualantstdevheadinghr;
  uint16_t gnssdualantstddevpitchhr;
  Reserved2 reservedSpace10;
  int32_t insHeight;
  Reserved4 reservedSpace11;
  int32_t insHeightPOI[8];
  uint32_t instimemsec;
  uint16_t instimeweek;
  int16_t leapseconds;
  GNSSPosition insPosAbs;
  GNSSPosition insPosRel;
  GNSSPosition insPosAbsPOI[8];
  GNSSPosition insPosRelPOI[8];
  Vector3 insVelHor;
  Vector3 insVelFrame;
  Vector3 insVelHorPOI[8];
  uint16_t insstddevlat;
  uint16_t insstddevlong;
  uint16_t insstddevheight;
  Reserved2 reservedSpace12;
  int8_t insstddevvelx;
  int8_t insstddevvely;
  int8_t insstddevvelz;
  int8_t insstddevroll;
  int8_t insstddevpitch;
  int8_t insstddevyaw;
  Reserved2 reservedSpace13;
  int16_t an1;
  int16_t an2;
  int16_t an3;
  int16_t an4;
  uint8_t kflatstimulated;
  uint8_t kflongstimulated;
  uint8_t kfsteadystate;
  unsigned char reservedSpace14[5];
  uint32_t gnssreceivererror;
  uint32_t gnssreceiverstatus;
};

struct AdmaDataV334 {
  AdmaStaticHeader staticHeader;
  AdmaDynamicHeader dynamicHeader;
  unsigned char gnssStatus;
  unsigned char signalInStatus;
  unsigned char miscStatus;
  int8_t statuscount;
  unsigned char kfStatus;
  unsigned char statusRobot;
  unsigned char reservedStatus1[2];
  unsigned char dataError1;
  unsigned char dataError2;
  unsigned char dataWarn1;
  unsigned char dataError3;
  Reserved4 reservedError1;
  SensorBody sensorsBodyX;
  SensorBody sensorsBodyY;
  SensorBody sensorsBodyZ;
  Vector3 ratesBody;
  Vector3 ratesHorizontal;
  Vector3 accBody;
  Vector3 accHorizontal;
  Vector3 accBodyPOI[8];
  Vector3 accHorizontalPOI[8];
  Vector2 extVelAnalog;
  int16_t extveldigx;
  int16_t extveldigy;
  uint16_t extveldigpulsesx;
  int16_t extveldigpulsesy;
  Vector2 extVelCorrected;
  Reserved4 reservedData1;
  Reserved4 reservedData2;
  Reserved4 reservedData3;
  Reserved4 reservedData4;
  Reserved4 reservedData5;
  Reserved4 reservedData6;
  Miscellaneous misc;
  Miscellaneous miscPOI[8];
  uint16_t trigrising1;
  uint16_t trigfalling1;
  uint16_t trigrising2;
  uint16_t trigfalling2;
  uint16_t trigrising3;
  uint16_t trigfalling3;
  uint16_t trigrising4;
  uint16_t trigfalling4;
  uint16_t systemta;
  int16_t systemtemp;
  uint16_t systemtimesinceinit;
  uint16_t systemdspload;
  GNSSPosition posAbs;
  GNSSPosition posRel;
  uint16_t gnssstddevlat;
  uint16_t gnssstddevlon;
  uint16_t gnssstddevheight;
  Reserved2 reservedSpace4;
  int16_t gnssvelframex;
  int16_t gnssvelframey;
  int16_t gnssvelframez;
  uint16_t gnssvellatency;
  Vector3 gnssStdDevVel;
  uint32_t gnsstimemsec;
  uint16_t gnsstimeweek;
  uint16_t gnsstrigger;
  uint16_t gnssdiffage;
  unsigned char gnsssatsused;
  unsigned char gnsssatsvisible;
  unsigned char gnsssatsdualantused;
  unsigned char gnsssatsdualantvisible;
  Reserved2 reservedSpace5;
  unsigned char gnsslogdelay;
  unsigned char gnssreceiverload;
  unsigned char gnssbasenr[4];
  Reserved2 reservedSpace6;
  int16_t insroll;
  int16_t inspitch;
  uint16_t insyaw;
  uint16_t gnsscog;
  int32_t gnssheight;
  int16_t undulation;
  Reserved2 reservedSpace7;
  uint32_t gnssDualAntTimeMsec;
  uint16_t gnssDualAntTimeWeek;
  Reserved2 reservedSpace8;
  uint16_t gnssDualAntHeading;
  int16_t gnssDualAntPitch;
  Reserved4 reservedSpace9;
  unsigned char gnssdualantstdevheading;
  unsigned char gnssdualantstddevpitch;
  uint16_t gnssdualantstdevheadinghr;
  uint16_t gnssdualantstddevpitchhr;
  Reserved2 reservedSpace10;
  int32_t insHeight;
  Reserved4 reservedSpace11;
  int32_t insHeightPOI[8];
  uint32_t instimemsec;
  uint16_t instimeweek;
  int16_t leapseconds;
  INSPosition insPos;
  INSPosition insPosPOI[8];
  Vector3 insVelHor;
  Vector3 insVelFrame;
  Vector3 insVelHorPOI[8];
  uint16_t insstddevlat;
  uint16_t insstddevlong;
  uint16_t insstddevheight;
  Reserved2 reservedSpace12;
  int8_t insstddevvelx;
  int8_t insstddevvely;
  int8_t insstddevvelz;
  int8_t insstddevroll;
  int8_t insstddevpitch;
  int8_t insstddevyaw;
  Reserved2 reservedSpace13;
  int16_t an1;
  int16_t an2;
  int16_t an3;
  int16_t an4;
  uint8_t kflatstimulated;
  uint8_t kflongstimulated;
  uint8_t kfsteadystate;
  unsigned char reservedSpace14[5];
  uint32_t gnssreceivererror;
  uint32_t gnssreceiverstatus;
};

struct AdmaDataV335 {
  AdmaStaticHeader staticHeader;
  AdmaDynamicHeader dynamicHeader;
  unsigned char gnssStatus;
  unsigned char signalInStatus;
  unsigned char miscStatus;
  int8_t statuscount;
  unsigned char kfStatus;
  unsigned char statusRobot;
  unsigned char reservedStatus1[2];
  unsigned char dataError1;
  unsigned char dataError2;
  unsigned char dataWarn1;
  unsigned char dataError3;
  Reserved4 reservedError1;
  SensorBody sensorsBodyX;
  SensorBody sensorsBodyY;
  SensorBody sensorsBodyZ;
  Vector3 ratesBody;
  Vector3 ratesHorizontal;
  Vector3 accBody;
  Vector3 accHorizontal;
  Vector3 accBodyPOI[8];
  Vector3 accHorizontalPOI[8];
  Vector2 extVelAnalog;
  int16_t extveldigx;
  int16_t extveldigy;
  uint16_t extveldigpulsesx;
  int16_t extveldigpulsesy;
  Vector2 extVelCorrected;
  Reserved4 reservedData1;
  Reserved4 reservedData2;
  Reserved4 reservedData3;
  Reserved4 reservedData4;
  Reserved4 reservedData5;
  Reserved4 reservedData6;
  Miscellaneous misc;
  Miscellaneous miscPOI[8];
  uint16_t trigrising1;
  uint16_t trigfalling1;
  uint16_t trigrising2;
  uint16_t trigfalling2;
  uint16_t trigrising3;
  uint16_t trigfalling3;
  uint16_t trigrising4;
  uint16_t trigfalling4;
  uint16_t systemta;
  int16_t systemtemp;
  uint16_t systemtimesinceinit;
  uint16_t systemdspload;
  GNSSPosition posAbs;
  GNSSPosition posRel;
  uint16_t gnssstddevlat;
  uint16_t gnssstddevlon;
  uint16_t gnssstddevheight;
  uint16_t gnssstddevcog;
  int16_t gnssvelframex;
  int16_t gnssvelframey;
  int16_t gnssvelframez;
  uint16_t gnssvellatency;
  Vector3 gnssStdDevVel;
  uint32_t gnsstimemsec;
  uint16_t gnsstimeweek;
  uint16_t gnsstrigger;
  uint16_t gnssdiffage;
  unsigned char gnsssatsused;
  unsigned char gnsssatsvisible;
  unsigned char gnsssatsdualantused;
  unsigned char gnsssatsdualantvisible;
  unsigned char gnsssatssinglefreq;
  unsigned char gnsssatsmultifreq;
  unsigned char gnsslogdelay;
  unsigned char gnssreceiverload;
  unsigned char gnssbasenr[4];
  unsigned char reservedSpace5[1];
  unsigned char gnsssatsdualantmultifreq;
  int16_t insroll;
  int16_t inspitch;
  uint16_t insyaw;
  uint16_t gnsscog;
  int32_t gnssheight;
  int16_t undulation;
  Reserved2 reservedSpace7;
  uint32_t gnssDualAntTimeMsec;
  uint16_t gnssDualAntTimeWeek;
  Reserved2 reservedSpace8;
  uint16_t gnssDualAntHeading;
  int16_t gnssDualAntPitch;
  Reserved4 reservedSpace9;
  unsigned char gnssdualantstdevheading;
  unsigned char gnssdualantstddevpitch;
  uint16_t gnssdualantstdevheadinghr;
  uint16_t gnssdualantstddevpitchhr;
  Reserved2 reservedSpace10;
  int32_t insHeight;
  uint16_t insyawrel;
  Reserved2 reservedSpace11;
  int32_t insHeightPOI[8];
  uint32_t instimemsec;
  uint16_t instimeweek;
  int16_t leapseconds;
  INSPosition insPos;
  INSPosition insPosPOI[8];
  Vector3 insVelHor;
  Vector3 insVelFrame;
  Vector3 insVelHorPOI[8];
  uint16_t insstddevlat;
  uint16_t insstddevlong;
  uint16_t insstddevheight;
  Reserved2 reservedSpace12;
  int8_t insstddevvelx;
  int8_t insstddevvely;
  int8_t insstddevvelz;
  int8_t insstddevroll;
  int8_t insstddevpitch;
  int8_t insstddevyaw;
  Reserved2 reservedSpace13;
  int16_t an1;
  int16_t an2;
  int16_t an3;
  int16_t an4;
  uint8_t kflatstimulated;
  uint8_t kflongstimulated;
  uint8_t kfsteadystate;
  unsigned char reservedSpace14[5];
  uint32_t gnssreceivererror;
  uint32_t gnssreceiverstatus;
};

#pragma pack(pop)

static_assert(sizeof(AdmaDataV32) == 768, "Unexpected ADMA v3.2 packet size");
static_assert(sizeof(AdmaDataV333) == 856, "Unexpected ADMA v3.3.3 packet size");
static_assert(sizeof(AdmaDataV334) == 856, "Unexpected ADMA v3.3.4 packet size");
static_assert(sizeof(AdmaDataV335) == 856, "Unexpected ADMA v3.3.5 packet size");

}  // namespace adma::protocol
